### PR TITLE
Fix api

### PR DESCRIPTION
**Pull request by adam2392**
PR Description
--------------

Closes: #10 
Closes: #23 

Address comment: https://github.com/adam2392/mne-icalabel/pull/31#discussion_r863584227

@mscheltienne  is this what you had in mind?

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by mscheltienne — APPROVED** [review]
Not exactly, I was thinking of also returning the `(n_components, n_class)` as a second dictionary ready to be converted to a DataFrame, thus returning 2 outputs.

But that looks even better!

From `mne_icalabel.label_compoents` -> simple output dict, ready to be converted to a DataFrame with the labels and the prediction probability for this component/label.
From `mne_icalabel.iclabel.iclabel_label_components` -> advance output with the prediction probabilities array `(n_components, n_class)`.

**Comment by adam2392** [comment]
FYI: I migrated all the testing datasets out into https://github.com/adam2392/mne-testing-icalabel-data

**Comment by mscheltienne** [comment]
Nice!

Do we need all the stuff in `mne_icalabel/conftest.py`? Especially the matplotlib or pyvista/3D stuff?

**Comment by adam2392** [comment]
Possibly not the pyvista stuff, but maybe good for future-proofing in case someone does like... 3D ica? 

We can remove though.

I just copy-pasted it real quick :p.

**Comment by mscheltienne** [comment]
yes, I figured 😆
Let's maybe clean it up and keep only what we need, but no rush ;)

**Pull request merged**
